### ISSUE TITLE
no jar for jvm in bintray

### ISSUE THREAD

**Issue by petrukhnov** [suparngp/kotlin-multiplatform-projects#32]
https://dl.bintray.com/suparnatural/kotlin-multiplatform/suparnatural-kotlin-multiplatform/

There is no jar for jvm (not android) in bintray repository.

E.g. specifying dependency for jvmMain is not possible

```
jvmMain {
            dependencies {
                implementation 'suparnatural-kotlin-multiplatform:fs-???:1.0.5'
            }
        }
```

Please, publish it.

**Comment by petrukhnov** [comment]
Sorry, didn't intend to close it.

**Comment by suparngp** [comment]
JVM is currently not supported for fs unfortunately. There is an open PR regarding this but it has been a while. I am currently dedicating all my time to the new graphql module and it will probably take me some time to wrap things up. If you have time, I could use your help with this PR. Else, I will try to squeeze it in sometime later.

https://github.com/suparngp/kotlin-multiplatform-projects/pull/12

**Comment by suparngp** [comment]
Should be resolved by #33

**Comment by petrukhnov** [comment]
Bintray still don't have jvm jar version, and there is no corresponding open issue.

**Comment by suparngp** [comment]
#40 will include this. I will release the binaries tomorrow (Thursday).
